### ISSUE TITLE
 current_user.schedule_tasks error

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#578]
```
Apr 28, 2016 11:10:32 PM org.apache.catalina.core.StandardWrapperValve invoke
INFO: Apr 28, 2016 11:10:32 PM org.apache.catalina.core.ApplicationContext log
INFO:
ActionView::Template::Error (Invalid identifier):
     6:   <div class="panel_content">
     7:     <ul>
     8:       <% count = 5 if ( count.nil? || count < 5) %>
     9:       <% current_user.schedule_tasks(:limit => count, :save => false) do |task| %>
    10:         <li>
    11:           <%= render :partial => 'tasks/task_line', :locals => { :task => task, :user => current_user } %>
    12:         </li>
  app/models/user.rb:274:in `tz'
  app/models/user.rb:343:in `schedule_tasks'
  app/views/tasks/_nextTasks.html.erb:9:in `_app_views_tasks__next_asks_html_erb___1986079792_26654'
  app/views/layouts/application.html.erb:10:in `block in _app_views_layouts_application_html_erb__1148003943_22200'
  app/views/layouts/application.html.erb:1:in `_app_views_layouts_application_html_erb__1148003943_22200'

```

**Comment by ari** [comment]
Also, this similar looking error:

```
Apr 28, 2016 11:04:58 PM org.apache.catalina.core.StandardWrapperValve invoke
INFO: Apr 28, 2016 11:04:58 PM org.apache.catalina.core.ApplicationContext log
INFO:
ActionView::Template::Error (Invalid identifier):
    4: <div class="clearfix log_entry access_level_<%=log.access_level_id%><%=" log_minor" unless log.comment? %>">
    5:   <div class="log_timestamp">
    6:     <span class="log_date">
    7:       <%= l(tz.utc_to_local(log.started_at), format: '%A') %><br/>
    8:       <%= l(tz.utc_to_local(log.started_at), format: '%d %b %Y') %>
    9:     </span>
   10:
  app/models/user.rb:274:in `tz'
  app/controllers/application_controller.rb:59:in `tz'
  app/views/activities/_log_row2.html.erb:7:in `_app_views_activities__log_row__html_erb__530891865_26736'
  app/views/tasks/_history.html.erb:8:in `_app_views_tasks__history_html_erb__2013274018_26650'
  app/views/tasks/_form.html.erb:33:in `block in _app_views_tasks__form_html_erb___365694586_22112'
  app/views/tasks/_form.html.erb:26:in `_app_views_tasks__form_html_erb___365694586_22112'
  app/helpers/tasks_helper.rb:4:in `render_task_form'
  app/views/tasks/_edit_form.html.erb:4:in `block in _app_views_tasks__edit_form_html_erb__29907411_22086'
  app/views/tasks/_edit_form.html.erb:4:in `_app_views_tasks__edit_form_html_erb__29907411_22086'
  app/views/tasks/edit.html.erb:3:in `_app_views_tasks_edit_html_erb___1808764804_22082'
  app/controllers/tasks_controller.rb:154:in `block in edit'
  app/controllers/tasks_controller.rb:153:in `edit'

```

**Comment by k41n** [comment]
@ari https://github.com/ari/jobsworth/pull/576
It should resolve this issue.

**Comment by ari** [comment]
I've already got that commit in production, so I think there is still a problem.

**Comment by ari** [comment]
Ignore previous comment... I havent' merged it!
